name: macondo_conductor
description: "Aplicación de Choferes, Manifiesto Puerta a Puerta, Escáner QR de Encomiendas y Despacho Admin - Macondo Express"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.17.2
  intl: ^0.20.2
  uuid: ^4.5.1
  url_launcher: ^6.3.2

  # Enlace al núcleo compartido Macondo Express
  macondo_core:
    path: ../macondo_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
